sudo: required

services:
  - docker

script:
  - docker build -t isitup.org .
  - docker run -d -e "PORT=80" -p 8080:80 isitup.org
  - wget --retry-connrefused --waitretry=1 --read-timeout=10 --timeout=10 -t 3 http://127.0.0.1:8080/
  - wget --retry-connrefused --waitretry=1 --read-timeout=10 --timeout=10 -t 3 http://127.0.0.1:8080/google.com
