sudo: required

services:
  - docker

script:
  - docker build -t isitup.org .
  - docker run -d -e "PORT=80" -p 8080:80 isitup.org
  - curl --retry 10 --retry-delay 5 -v http://localhost:8080
  - curl --retry 10 --retry-delay 5 -v http://localhost:8080/google.com
